import type { Goal } from '../types/goal'
import type { MonthlyBudget } from '../types/monthlyBudget'
import type { AllocationResult } from '../types/Allocation'


/**
 * Defines the common contract for all allocation strategies.
 *
 * Each allocation strategy must implement the allocate()
 * method to determine how available monthly budgets are
 * distributed across the user's savings goals.
 */
export interface AllocationStrategy {

  /**
   * Generates allocation results for the provided goals
   * and available monthly budgets.
   *
   * @param goals - Savings goals to be considered during allocation.
   * @param budgets - Available monthly budgets for allocation.
   * @returns The allocation results generated by the strategy.
   */
  allocate(
    goals: Goal[],
    budgets: MonthlyBudget[]
  ): AllocationResult[]
}